module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'body-max-line-length': [2, 'always', 100],
    'header-max-length': [2, 'always', 72],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'gateway',
        'auth',
        'users',
        'catalog',
        'university',
        'resources',
        'bookings',
        'requests',
        'events',
        'notifications',
        'pqrs',
        'storage',
      ],
    ],
  },
};
